CREATE TABLE user_preferences
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email_notifications_enabled BOOLEAN                                 NOT NULL,
    push_notifications_enabled  BOOLEAN                                 NOT NULL,
    sms_notifications_enabled   BOOLEAN                                 NOT NULL,
    marketing_emails_enabled    BOOLEAN                                 NOT NULL,
    security_alerts_enabled     BOOLEAN                                 NOT NULL,
    product_updates_enabled     BOOLEAN                                 NOT NULL,
    notification_frequency      VARCHAR(20)                             NOT NULL,
    quiet_hours_start           time WITHOUT TIME ZONE,
    quiet_hours_end             time WITHOUT TIME ZONE,
    timezone                    VARCHAR(50)                             NOT NULL,
    created_at                  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id                     BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_preferences PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(100)                            NOT NULL,
    last_name  VARCHAR(100)                            NOT NULL,
    phone      VARCHAR(20),
    active     BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_preferences
    ADD CONSTRAINT uc_user_preferences_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE INDEX idx_user_preferences_email_enabled ON user_preferences (email_notifications_enabled);

CREATE INDEX idx_user_preferences_push_enabled ON user_preferences (push_notifications_enabled);

CREATE INDEX idx_users_active ON users (active);

CREATE INDEX idx_users_created_at ON users (created_at);

CREATE INDEX idx_users_email ON users (email);

ALTER TABLE user_preferences
    ADD CONSTRAINT FK_USER_PREFERENCES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_user_preferences_user_id ON user_preferences (user_id);